### ISSUE TITLE
Pushbullet Input node cannot reconnect after disconnection

### ISSUE THREAD

**Issue by kporowski** [node-red/node-red-nodes#171]
I have a simple flow that receives Pushbullet messages. It works fine for couple of hours at most until Pushbullet gets disconnected. This is what I can see in NodeRED output:
` [error] [pushbullet in:ReceivePushbullet] Error: read ETIMEDOUT`

This makes Pushbullet Input node unusable. What is interesting Pushbullet Output nodes work fine at the same time, ie. they are not affected by this error. I am able to send messaages, even if I can't receive them. The only workaround I have found is to redeploy flows. Pushbullet Input node should be able to reconnect/reinitialize when in '**disconnected**' state without a need of manual redeployment of flows.

My env:
- NodeRED: 0.13.1
- NodeJS: 0.10.25
- Raspberry Pi B with raspbmc

**Comment by dceejay** [comment]
Hi I have pushed a fix that tries to reconnect to the server every 15 secs if there is an error (and we aren't closing cleanly).... please let me know if it fixes it for you... (it does for me if I physically break the connection here - but I didn't wait 2 hours ;-)

**Comment by kporowski** [comment]
Thanks for the fix, it looks promising :+1:.
I have just updated pushbullet node. I'll let you know if it fixes my issue.

**Comment by kporowski** [comment]
I am afraid it haven't solved my issue. Last night I got notification that Pushbullet Input node got disconnected. I got 2 status updates:
1. `error, see log`
2. `disconnected`

After that, Pushbullet Input node stayed in `disconnected` status with gray circle next to it.
This is what I see in NodeRED output:
`[error] [pushbullet in:ReceivePushbullet] Error: read ETIMEDOUT`

Is there anything else I can do to see more verbose output? I have already used `-v` option and set logging console level to `debug` in settings.js.

**Comment by eschava** [comment]
still reproduced
I had network reconnection but no messages in log related to "pushbullet in" node and also status of the node wasn't changed. It's still "connected" but new incoming messages are ignored

**Comment by eschava** [comment]
After research, I've found that tcp connections to pushbullet server are still shown by netstat with "FIN_WAIT2" status and aren't removed even after re-deploy.
Googling says that this status could be specific for node.js application

**Comment by eschava** [comment]
A couple of links:

https://github.com/nodejs/node-v0.x-archive/issues/3613
https://github.com/soplwang/node-ka-patch
https://stackoverflow.com/questions/12999740/nodejs-socket-fin-wait2#comment17655333_12999740
`
 I was closing connection with end() but that would just leave it in FIN_WAIT2 status. After end() I added destroy() to force close it and there are no more FIN_WAIT2 connections, or if there are they get removed after tcp_fin_timeout. `
