### ISSUE TITLE
Error when sending email

### ISSUE THREAD

**Issue by AnandJhaveri** [node-red/node-red-nodes#942]
I am getting the following error message when sending email.

"Error: Can not use IPv4 addresses with current network"

I am using the latest version of node-red-node-email.
It is running on a raspberry pi.

Please could you suggest what I need to do to resolve this?

Regards,
Anand.

**Comment by hardillb** [comment]
Please fill out the full template you were shown when you opened the issue, it saves us having you ask you supply a lot of information we need to be able to help you.

Please supply:

- Node-RED version
- node-red-node-email version
- NodeJS version
- OS version

Also have checked that the machine Node-RED is running on actually has an IPv4 address from the network? The error implies you may be connected to an IPv6 only network.

**Comment by AnandJhaveri** [comment]
Sorry, I did not see the template when framing the message.


   - Node-RED version : 3.0.0
   - node-red-node-email version 1.17.0
   - NodeJS version: 14.19.3
   - OS version: Raspbian 11 (bullseye)


I rebooted the pi and the router and the problem seems to have been
resolved for the moment.

What should I do next?

Regards,
Anand.

**Comment by MikeGitHubRPi** [comment]
Hello friends,

Same error and still not working after reboot.

Any help, please.

Regards, Mike.

**Comment by hardillb** [comment]
@MikeGitHubRPi This is most likely a problem with your local network set up.

Rebooting will only help if that forces your local network infrastructure (e.g. router) to issue you a new IPv4 address.

You need to check that the Pi is actually getting a routable IPv4 address so it can connect out to the internet.

**Comment by MikeGitHubRPi** [comment]
Hello herdillb, thank you for your answer.

I've checked it and I can connect out to internet without any problem.

Any idea?

thank you

**Comment by hardillb** [comment]
Not without a LOT more information.

This is a closed issue, please open a new one, fill out the template with your system details and include details about your network setup e.g. the output of `ip a` and `ip r` which will show what IP addresses your machine has and what routing is has setup. (under most situations this will be IP addresses out of the RFC 1918 range so will not expose any information that would allow people to connect to your device)
