### ISSUE TITLE
email unable to send without subject and body

### ISSUE THREAD

**Issue by rayzorben** [node-red/node-red-nodes#959]
### Which node are you reporting an issue on?
`social/email`

### What are the steps to reproduce?

1. Add a node which has a msg.payload that is a binary buffer
2. Add a node which uses `node-red-node-email` to send email
3. Configure node to use email server such as gmail
4. Try to configure node NOT to use a subject line or body

### What happens?
Email is sent with Subject: Message from Node-RED
Email is sent with Body: File from Node-RED is attached: attachment.jpg

### What do you expect to happen?
Allow me to configure the subject and body to be blank.

I am wanting to send text messages from camera alert images. I use 4254440000@vzwpix.com as an example. I don't want to show more than just the picture.

**Comment by dceejay** [comment]
ah yes - good old "" being falsey...  will fix.

**Comment by dceejay** [comment]
fix pushed in v1.18.2  you can now set msg.topic = ''  msg.description = '' to set the subject and body to be blank

**Comment by rayzorben** [comment]
Awesome, thanks!

**Comment by rayzorben** [comment]
Awesome, thanks!

**Comment by rayzorben** [comment]
Am I doing this right? I checked and node updated node-red-node-email to 1.18.2 this morning, i made this change and redeployed but I am still getting the same subject/body

![image](https://user-images.githubusercontent.com/7737834/200622098-012d73ca-a209-42e5-86ab-bef74f866b8b.png)

**Comment by dceejay** [comment]
Should be - (and `msg.payload` is the binary buffer of the image, and `msg.filename` is the name that you want to give the file - what are you seeing ?
